### ISSUE TITLE
add auto fix

### ISSUE THREAD

**Issue by batazor** [ckaznocha/intrange#20]
auto fix from `for i := 0; i < 100; i++` to `for i := range 100`

**Comment by cespare** [comment]
I made a (very quick and dirty) tool for myself which changes `for` statements to use range-over-int if possible. In case it's useful, here's the bit that does the editing: https://github.com/cespare/misc/blob/188b9f2b335bef60681a649d5a0e344d0f7446fe/useintrange/useintrange.go#L258-L297

**Comment by ckaznocha** [comment]
Thanks @cespare, for clarity the delay in adding autofixes is more about compatibility with golangci-lint.

They were not added initially because golangci-lint had a minimum go version as `1.21` as ranging over integers was introduced in go `1.22` it would have been awkward to change working code to unsupported code. golangci-lint has since added version detection so that is no longer a concern.

In #28 I added an autofix to simplify some ranges using `analysis.SuggestedFix` however golangci-lint doesn't support `analysis.SuggestedFix`. See https://github.com/golangci/golangci-lint/issues/1779.

I plan on adding more autofixes when golangci-lint can support `analysis.SuggestedFix` but I'm not sure in the meantime I'd try to use their bespoke autofix system. I would be happy to review a PR if anyone wanted to contribute a golangci-lint compatible autofix.

**Comment by ckaznocha** [comment]
Implement suggested fixes for:
- [x] 3 statement loops where the key is not used in the body (#39)
- [x] 3 statement loops where the key is used in the body (#34, #35)
- [x] range loops with redundant len where the key is not used in the body (#28)
- [x] range loops with redundant len where the key is used in the body (#28)

No suggested fixes for:
- [x] 3 statement loops where the key belongs to a different scope (#37) ref: https://github.com/ckaznocha/intrange/issues/33#issuecomment-2408270614
